var htmlHead="Head";
var htmlTable="table";
var htmlSpan="true";
var htmlBody="bodytag";
var htmlForm="forms";
var htmlButton="click";
var htmlMain="main";
var htmlList="list";
var htmlPlaceholder="100px";
var htmlElements="elements";
var htmlStyle = 10;
var htmlTags=500;
var htmlUlist=true;
var htmlScript=false;
var htmlHeader="";
var htmlParagraph;
var htmlOg=null;
var htmlIntro;
var htmlSection;
var htmlCenter;
var htmlFooter;
var htmlAnchor;
var htmlHref;
var htmlNavigation;
var htmlImg;
var htmlBootstrap;
var htmlPage;
var htmlDiv;
var htmlTailwind;
console.log(htmlHead);
console.log(htmlStyle);
console.log(htmlUlist);
console.log(htmlIntro);
console.log(htmlOg);
